application: {}
environments:
  acc: {}
  dev: {}
  prod:
    allow_drop_all: 'True'
    api_path: /api
    description: Beweeghuis PHT Proof of Principle
    ip: 0.0.0.0
    jwt_secret_key: 95161ee4-dcfd-11ed-b875-2f6e36e39b10
    logging:
      backup_count: 5
      datefmt: '%Y-%m-%d %H:%M:%S'
      file: beweeghuis-poc.log
      format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
      level: DEBUG
      max_size: 1024
      use_console: true
    port: '5000'
    uri: sqlite:///default.sqlite
  test: {}
